<?php

$datos = [
    array(
            'nombre' => "Tradicional",
            'precio' => 75,
            'imagen' => 'ramen_01',
            'categoriaId' => 1,
            'disponible' => true,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chiken",
        'precio' => 85,
        'imagen' => 'ramen_02',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Vegano",
        'precio' => 85,
        'imagen' => 'ramen_03',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Ribu",
        'precio' => 95,
        'imagen' => 'ramen_04',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Niku",
        'precio' => 100,
        'imagen' => 'ramen_05',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Sopporo",
        'precio' => 100,
        'imagen' => 'ramen_06',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chikin",
        'precio' => 110,
        'imagen' => 'ramen_07',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Shio",
        'precio' => 100,
        'imagen' => 'ramen_08',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
    'nombre' => "Ika",
    'precio' => 125,
    'imagen' => "ramen_09",
    'categoriaId' => 1,
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Rayito",
        'precio' => 125,
        'imagen' => 'ramen_10',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Daco",
        'precio' => 155,
        'imagen' => 'ramen_11',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Nikkis",
        'precio' => 140,
        'imagen' => 'ramen_12',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kuro",
        'precio' => 150,
        'imagen' => 'ramen_13',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Haku",
        'precio' => 170,
        'imagen' => 'ramen_14',
        'categoriaId' => 1,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Yakisoba",
        'precio' => 90,
        'imagen' => 'yakisoba_01',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Shoya",
        'precio' => 100,
        'imagen' => 'yakisoba_02',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Rayito soba",
        'precio' => 125,
        'imagen' => 'yakisoba_03',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),array(
        'nombre' => "Chizzu soba",
        'precio' => 125,
        'imagen' => 'yakisoba_04',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Bacon soba",
        'precio' => 105,
        'imagen' => 'yakisoba_05',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Vegano",
        'precio' => 85,
        'imagen' => 'yakisoba_06',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Pinky soba",
        'precio' => 105,
        'imagen' => 'yakisoba_07',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tamago",
        'precio' => 100,
        'imagen' => 'yakisoba_08',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Carbonara",
        'precio' => 100,
        'imagen' => 'yakisoba_09',
        'categoriaId' => 2,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chessake frio de tortuga",
        'precio' => 60,
        'imagen' => 'postres_01',
        'categoriaId' => 3,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chessake frio de zarzamora",
        'precio' => 60,
        'imagen' => 'postres_02',
        'categoriaId' => 3,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Flan napolitano de queso crema",
        'precio' => 55,
        'imagen' => 'postres_03',
        'categoriaId' => 3,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tiramisu",
        'precio' => 60,
        'imagen' => 'postres_04',
        'categoriaId' => 3,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Charola familiar",
        'precio' => 250,
        'imagen' => 'charola_01',
        'categoriaId' => 4,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kumo charola",
        'precio' => 280,
        'imagen' => 'charola_02',
        'categoriaId' => 4,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tokoshuma",
        'precio' => 250,
        'imagen' => 'charola_03',
        'categoriaId' => 4,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Supreme",
        'precio' => 420,
        'imagen' => 'charola_04',
        'categoriaId' => 4,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Inari",
        'precio' => 250,
        'imagen' => 'charola_05',
        'categoriaId' => 4,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Balls",
        'precio' => 20,
        'imagen' => 'aperitivo_01',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Orden de balls",
        'precio' => 75,
        'imagen' => 'aperitivo_02',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Orden de takoyakis",
        'precio' => 80,
        'imagen' => 'aperitivo_03',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Oniguiri",
        'precio' => 30,
        'imagen' => 'aperitivo_04',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Oniguiri empanizado",
        'precio' => 40,
        'imagen' => 'aperitivo_05',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Orden de temari sushi",
        'precio' => 90,
        'imagen' => 'aperitivo_06',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Oniaratzu",
        'precio' => 65,
        'imagen' => 'aperitivo_07',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Okonomiyaki",
        'precio' => 65,
        'imagen' => 'aperitivo_08',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Yakimeshi",
        'precio' => 60,
        'imagen' => 'aperitivo_09',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kushiagues",
        'precio' => 20,
        'imagen' => 'aperitivo_10',
        'categoriaId' => 5,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Horchata (vaso)",
        'precio' => 25,
        'imagen' => 'bebida_01',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Jamaica (vaso)",
        'precio' => 25,
        'imagen' => 'bebida_02',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Tamarindo (vaso)",
        'precio' => 25,
        'imagen' => 'bebida_03',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Horchata (jarra)",
        'precio' => 25,
        'imagen' => 'bebida_04',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Jamaica (jarra)",
        'precio' => 25,
        'imagen' => 'bebida_05',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aua de Tamarindo (jarra)",
        'precio' => 25,
        'imagen' => 'bebida_06',
        'categoriaId' => 6,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Oreo",
        'precio' => 45,
        'imagen' => 'frappes_01',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Medias de seda",
        'precio' => 45,
        'imagen' => 'frappes_02',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Cajeta",
        'precio' => 45,
        'imagen' => 'frappes_03',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kahlua",
        'precio' => 45,
        'imagen' => 'frappes_04',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Rompope",
        'precio' => 45,
        'imagen' => 'frappes_05',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chocolate",
        'precio' => 45,
        'imagen' => 'frappes_06',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "M&N",
        'precio' => 50,
        'imagen' => 'frappes_07',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chocoreta",
        'precio' => 50,
        'imagen' => 'frappes_08',
        'categoriaId' => 7,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Soya",
        'precio' => 10,
        'imagen' => 'extras_01',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tampico",
        'precio' => 10,
        'imagen' => 'extras_02',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chiles toreados",
        'precio' => 15,
        'imagen' => 'extras_03',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Sriracha",
        'precio' => 15,
        'imagen' => 'extras_04',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aderezo de chipotle",
        'precio' => 10,
        'imagen' => 'extras_05',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Teriyaki",
        'precio' => 10,
        'imagen' => 'extras_06',
        'categoriaId' => 8,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Empanizado",
        'precio' => 75,
        'imagen' => 'calientes_01',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Mar y tiera",
        'precio' => 90,
        'imagen' => 'calientes_02',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Apachito",
        'precio' => 90,
        'imagen' => 'calientes_03',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Karamaki",
        'precio' => 85,
        'imagen' => 'calientes_04',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Chuky",
        'precio' => 90,
        'imagen' => 'calientes_05',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Acapulco",
        'precio' => 105,
        'imagen' => 'calientes_06',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Pig",
        'precio' => 90,
        'imagen' => 'calientes_07',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Alika",
        'precio' => 105,
        'imagen' => 'calientes_08',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Mexican",
        'precio' => 100,
        'imagen' => 'calientes_09',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Quiquin",
        'precio' => 100,
        'imagen' => 'calientes_10',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Spoody",
        'precio' => 100,
        'imagen' => 'calientes_11',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Saru",
        'precio' => 90,
        'imagen' => 'calientes_12',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Bacon",
        'precio' => 105,
        'imagen' => 'calientes_13',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Oppa",
        'precio' => 105,
        'imagen' => 'calientes_14',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Uzz",
        'precio' => 140,
        'imagen' => 'calientes_15',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tempura",
        'precio' => 105,
        'imagen' => 'calientes_16',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kumo",
        'precio' => 150,
        'imagen' => 'calientes_17',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "León",
        'precio' => 140,
        'imagen' => 'calientes_18',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Trompo",
        'precio' => 110,
        'imagen' => 'calientes_19',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Xalapeño Pepper",
        'precio' => 110,
        'imagen' => 'calientes_20',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Augusto",
        'precio' => 150,
        'imagen' => 'calientes_21',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Metztli",
        'precio' => 165,
        'imagen' => 'calientes_22',
        'categoriaId' => 9,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Tradicional",
        'precio' => 75,
        'imagen' => 'frios_01',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Aguacate",
        'precio' => 75,
        'imagen' => 'frios_02',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Platano",
        'precio' => 75,
        'imagen' => 'frios_03',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "California maki",
        'precio' => 70,
        'imagen' => 'frios_04',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Atun",
        'precio' => 85,
        'imagen' => 'frios_05',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Laika",
        'precio' => 95,
        'imagen' => 'frios_06',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Momo",
        'precio' => 105,
        'imagen' => 'frios_07',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Mousy",
        'precio' => 100,
        'imagen' => 'frios_08',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Futomaki",
        'precio' => 90,
        'imagen' => 'frios_09',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "King",
        'precio' => 85,
        'imagen' => 'frios_10',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Amargadita",
        'precio' => 90,
        'imagen' => 'frios_11',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Sakura",
        'precio' => 105,
        'imagen' => 'frios_12',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Loki",
        'precio' => 105,
        'imagen' => 'frios_13',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Cuba",
        'precio' => 100,
        'imagen' => 'frios_14',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Panchito",
        'precio' => 80,
        'imagen' => 'frios_15',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Coco",
        'precio' => 105,
        'imagen' => 'frios_16',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Junior",
        'precio' => 105,
        'imagen' => 'frios_17',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Platano Supreme",
        'precio' => 105,
        'imagen' => 'frios_18',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Yolotl",
        'precio' => 105,
        'imagen' => 'frios_19',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Ligth",
        'precio' => 110,
        'imagen' => 'frios_20',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
    array(
        'nombre' => "Kani",
        'precio' => 140,
        'imagen' => 'frios_21',
        'categoriaId' => 10,
        'disponible' => true,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ),
];